### ISSUE TITLE
Difference between this plugin and com.google.appengine:app-maven-plugin?

### ISSUE THREAD

**Issue by Orbyt** [GoogleCloudPlatform/app-maven-plugin#151]
What is the difference between this plugin and `com.google.appengine:app-maven-plugin:1.9.21` as found [here?](https://mvnrepository.com/artifact/com.google.appengine/appengine-maven-plugin)

They share the same name, and appear to overlap in functionality. For example, to run a dev server with this plugin, one would run `mvn appengine:start`, however with the other plugin, `mvn appengine:devserver` is used.

What is the difference? Why is there 2 plugins?

**Comment by meltsufin** [comment]
The `com.google.appengine:app-maven-plugin:1.9.21` plugin only supports App Engine Standard, while this one is based on the Cloud SDK and supports both App Engine Standard and App Engine Flexible.

**Comment by Orbyt** [comment]
@meltsufin There must be more to it than that. The `com.google.appengine:app-maven-plugin:1.9.21` has a significantly greater number of goals than this plugin, which contains ~6 maven goals.

**Comment by meltsufin** [comment]
You're right, the original plugin has more goals, but many of those goals were not added to this plugin because they make more sense to be performed directly via the Cloud SDK CLI (gcloud).
If you're deploying your app to App Engine Standard, you have a choice between the original plugin and this one, but if you're deploying to App Engine Flexible, this is the plugin to use.
I know it's a bit confusing, but I hope this helps.

**Comment by Orbyt** [comment]
@meltsufin I see, thank you for the information.

**Comment by patflynn** [comment]
@Orbyt we'll be adding goals for cron, dos, index updates, etc to this plugin shortly.
