### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.appengine.repackaged.org.codehaus.jackson.node.ObjectNode

### ISSUE THREAD

**Issue by wholegroup** [GoogleCloudPlatform/app-maven-plugin#201]
Calling `curl http://localhost:8080/_ah/api` of a simple project (eg [helloworld-new-plugins](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine/helloworld-new-plugins)) causes an exception like this:
```
[INFO] GCLOUD: 2017-07-11 01:20:32.105:WARN:oejs.ServletHandler:qtp2091156596-22: Error for /_ah/api/
[INFO] GCLOUD: java.lang.NoClassDefFoundError: com/google/appengine/repackaged/org/codehaus/jackson/node/ObjectNode
[INFO] GCLOUD:  at java.lang.Class.getDeclaredConstructors0(Native Method)
[INFO] GCLOUD:  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[INFO] GCLOUD:  at java.lang.Class.getConstructor0(Class.java:3075)
[INFO] GCLOUD:  at java.lang.Class.newInstance(Class.java:412)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2481)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1285)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:615)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[INFO] GCLOUD:  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[INFO] GCLOUD:  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
[INFO] GCLOUD:  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
[INFO] GCLOUD:  at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[INFO] GCLOUD:  at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
[INFO] GCLOUD:  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[INFO] GCLOUD:  at org.eclipse.jetty.server.Server.handle(Server.java:534)
[INFO] GCLOUD:  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
[INFO] GCLOUD:  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[INFO] GCLOUD:  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
[INFO] GCLOUD:  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
[INFO] GCLOUD:  at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] GCLOUD:  at java.lang.Thread.run(Thread.java:745)
```

p.s. but the main pain is probably that the error doesn't allow to set up endpoints via [endpoints-framework-guice](https://github.com/cloudendpoints/endpoints-java/tree/master/endpoints-framework-guice)

**Comment by patflynn** [comment]
@loosebazooka have you had a chance to triage this issue?

**Comment by loosebazooka** [comment]
can you share your pom.xml with us, this kind of error usually indicates a dependency mismatch or something of that kind.

**Comment by chanseokoh** [comment]
Easily reproducible. There is an internal bug I opened last Thursday or Friday for this.

**Comment by loosebazooka** [comment]
It appears this bug manifests itself when you don't define the endpoints servlet in web.xml. I don't know how guice handles endpoints, but if you define the `EndpointsServlet` as described in the endpoints docs the devappserver seems to load in some other libraries and things work fine. Is guice populating the web.xml for you or something?

**Comment by wholegroup** [comment]
@loosebazooka Guice binds `EndpointsServlet` in runtime (see [here](https://github.com/cloudendpoints/endpoints-java/blob/master/endpoints-framework-guice/src/main/java/com/google/api/server/spi/guice/EndpointsModule.java#L91)), web.xml contains only Guice listener and filter.

**Comment by loosebazooka** [comment]
Gotcha, so this appears to be a issue with the devappserver and endpoints. @tangiel @ludoch ?

**Comment by tangiel** [comment]
@wholegroup can you have `GuiceFilter` bind to `/_ah/api/*` and not just `*`? I think this works as a workaround. This is happening because dev server defaults to the Endpoints v1 dev servlets.

**Comment by wholegroup** [comment]
@tangiel I've changed `web.xml` (see below), but calling an endpoint still throws an exception.

```
[INFO] GCLOUD: Jul 19, 2017 12:16:47 AM com.google.appengine.tools.development.DevAppServerImpl doStart
[INFO] GCLOUD: INFO: Dev App Server is now running
[INFO] GCLOUD: 2017-07-19 00:16:55.860:WARN:oejs.ServletHandler:qtp1508395126-18: Error for /_ah/api/general/v2/rates
[INFO] GCLOUD: java.lang.NoClassDefFoundError: com/google/appengine/repackaged/org/codehaus/jackson/node/ObjectNode
[INFO] GCLOUD:  at java.lang.Class.getDeclaredConstructors0(Native Method)
```

web.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
		  http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" version="2.5">
    <listener>
        <listener-class>com.wholegroup.project_id.api.guice.GuiceConfig</listener-class>
    </listener>
    <filter>
        <filter-name>guiceFilter</filter-name>
        <filter-class>com.google.inject.servlet.GuiceFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>guiceFilter</filter-name>
        <url-pattern>/_ah/api/*</url-pattern>
    </filter-mapping>
</web-app>
```

guice module:
```java
public class GuiceEndpoints extends EndpointsModule {

    /** Endpoints url pattern. */
    private static final String URL_PATTERN = "/_ah/api/*";

    /** Project id. */
    private static final String PROJECT_ID = "project_id";

    /** Service name. */
    private static final String SERVICE_NAME = "api.endpoints.project_id.cloud.goog";

    /**
     * Configures endpoints servlet.
     */
    @Override
    protected void configureServlets() {
        configureEndpoints(URL_PATTERN, ImmutableList.of(
            RatesGeneralV2Endpoint.class
        ));
        filter(URL_PATTERN).through(ServiceManagementConfigFilter.class);
        filter(URL_PATTERN).through(GoogleAppEngineControlFilter.class, ImmutableMap.of(
            "endpoints.projectId", PROJECT_ID,
            "endpoints.serviceName", SERVICE_NAME));
    }
}
```

**Comment by ceosilvajr** [comment]
+1

**Comment by rahultongia** [comment]
+1

**Comment by loosebazooka** [comment]
@ceosilvajr @rahultongia are you both using guice as well?

**Comment by tangiel** [comment]
I think this may be a Java 8 runtime issue @ludoch

**Comment by rahultongia** [comment]
@loosebazooka yes using guice with endpoints on java8

**Comment by ceosilvajr** [comment]
Hi @loosebazooka yes I'm using Guice but not in java8.
cc: @tangiel

**Comment by tangiel** [comment]
@ceosilvajr can you paste your stack trace just to verify please?

**Comment by mrankitsinghal** [comment]
I am also getting the same issue on Java 8 runtime. Here I am attaching stack trace.

`[INFO] 2017-08-23 14:02:12.195:WARN:oejs.ServletHandler:qtp1028780142-178: Error for /_ah/api/explorer
[INFO] java.lang.NoClassDefFoundError: com/google/appengine/repackaged/org/codehaus/jackson/node/ObjectNode
[INFO] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[INFO] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[INFO] 	at java.lang.Class.getConstructor0(Class.java:3075)
[INFO] 	at java.lang.Class.newInstance(Class.java:412)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2481)
[INFO] 	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1285)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:615)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[INFO] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
[INFO] 	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[INFO] 	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[INFO] 	at org.eclipse.jetty.server.Server.handle(Server.java:534)
[INFO] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
[INFO] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[INFO] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
[INFO] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
[INFO] 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: 
[INFO] java.lang.ClassNotFoundException: com.google.appengine.repackaged.org.codehaus.jackson.node.ObjectNode
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:195)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[INFO] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[INFO] 	at java.lang.Class.getConstructor0(Class.java:3075)
[INFO] 	at java.lang.Class.newInstance(Class.java:412)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2481)
[INFO] 	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1285)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:615)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[INFO] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
[INFO] 	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[INFO] 	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[INFO] 	at org.eclipse.jetty.server.Server.handle(Server.java:534)
[INFO] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
[INFO] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[INFO] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
[INFO] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
[INFO] 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by tangiel** [comment]
@mrankitsinghal is this on dev server? It looks like it. Can you post your `web.xml`?

**Comment by chanseokoh** [comment]
Internal bug: b/63715943

**Comment by ludoch** [comment]
Does not seem to be a new bug:
With the original plugin, I tried version
Release: 1.9.34
Timestamp: Thu Feb 11 11:36:15 PST 2016
of the GAE SDK and still see this issue.
As it was mentioned, "It appears this bug manifests itself when you don't define the endpoints servlet in web.xml"

So basically you are trying to access endpoints api registry when you do not need/use endpoints. 
Corner case issue.

**Comment by chanseokoh** [comment]
I don't know anything about Endpionts and Guice, but based on https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/201#issuecomment-316144285, it seems like Endpoints are being used in this case, although the servlet is not defined in `web.xml`.

**Comment by tangiel** [comment]
@ludoch Someone mentioned that adding a `url-mapping` to `/_ah/api/*` didn't fix the issue, despite it historically being the way to do so. Maybe in Java 8 this workaround doesn't work?

@chanseokoh Yes, the dev server base `web.xml` includes the Endpoints dev servlets. I wonder how soon we could remove that given the deprecation notice.

**Comment by henriquefm** [comment]
One workaround is to add a dummy api class to your web.xml:
`@Api()
public class Dummy {}`

In web.xml, add the EndpointsServlet pointing to the Dummy class:
```xml
	<servlet>
		<servlet-name>SystemServiceServlet</servlet-name>
		<servlet-class>com.google.api.server.spi.EndpointsServlet</servlet-class>
		<init-param>
			<param-name>services</param-name>
			<param-value>path.to.Dummy</param-value>
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>SystemServiceServlet</servlet-name>
		<url-pattern>/_ah/api/*</url-pattern>
	</servlet-mapping>
```

In web.xml, you keep your regular Guice listener and filter, and in your EndpointsModule class you put the actual api classes. I don't know if there are any bad side effects to this, but it can keep the development going until the issue is fixed.

**Comment by wiradikusuma** [comment]
I don't use Guice, just plain old GAE Java 7, and I encounter this bug.

**Comment by loosebazooka** [comment]
There are 2 reasons this could happen
1. You are accidentally importing this class from repackaged
2. You need to upgrade your version of the cloud sdk to latest.

**Comment by wiradikusuma** [comment]
@loosebazooka You're right, I downgraded to `gcloud components update --version 159.0.0`, because of issue with Search API (https://issuetracker.google.com/issues/63732823). Please advise.

**Comment by clembou590** [comment]
I had this issue while I was trying to configure in the guice module all the filters and servlet.
I then used this sample code:
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/endpoints-v2-guice
and I ran into the exact same error...
I upgraded gcloud --> problem solved!

**Comment by wholegroup** [comment]
I confirm, 
it works well now after upgrading gcloud
