### ISSUE TITLE
Failed to run devappserver: NoSuchFileException: appengine-web.xml

### ISSUE THREAD

**Issue by RayDiazVega** [GoogleCloudPlatform/app-maven-plugin#421]
Hello

I'm trying to run a spring boot maven flex app with App Engine, I'm using `java 1.8.0_251`, `Apache Maven 3.6.3`, `Google Cloud SDK [296.0.0]`, `app-engine-java: [1.9.80]`,  `IntelliJ IDEA 2020.1.2`, this is the appengine plugin in my pom:

```
<plugin>
  <artifactId>appengine-maven-plugin</artifactId>
  <configuration>
    <deploy.projectId>my-project</deploy.projectId>
    <deploy.version>GCLOUD_CONFIG</deploy.version>
  </configuration>
  <groupId>com.google.cloud.tools</groupId>
  <version>2.2.0</version>
</plugin>
```

And this is part of my app.yaml:

```
service: reports
env: flex
runtime: java
runtime_config:
  jdk: openjdk8
```

So when I execute my project with the command `mvn package appengine:run`, I get the following error:

`Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.2.0:run (default-cli) on project reports: Failed to run devappserver: java.nio.file.NoSuchFileException: C:\Users\ACER1\Documents\proyects\reports\target\reports-0.0.1-SNAPSHOT\WEB-INF\appengine-web.xml`

When I generate the project in [start.spring.io](https://start.spring.io/), no appengine-web.xml file was generated. Do I need to add this file on my own for the `mvn package appengine:run` command works?

Thanks for your time.

**Comment by loosebazooka** [comment]
`appengine:run` is not available for flex projects.

**Comment by chanseokoh** [comment]
The flex and standard are two different environments, and there are a lot of factors you should consider when choosing an environment that's right for you. Only because the standard env has `appengine:run` doesn't sound like a logical choice to switch to standard. However, your app is just a hello-world app, so I think it's still good to use standard. You app is a Spring Boot project, so the runtime you can use on standard is [Java 11 Standard Environment](https://cloud.google.com/appengine/docs/standard/java11/runtime). (Unless you do something very weird, Java 8 apps will have no problem on Java 11 JVM.)

> Or is there some other way to run my flex project locally?

Spring Boot projects supply a server for you. Whether or not using flex, just run [`mvn spring-boot:run`](https://spring.io/guides/gs/spring-boot/#_run_the_application) and your app will listen on `localhost:8080` by default. You won't do `appengine:run`; that's for traditional Servlet-based apps with Java 8 Standard Environment.

**Comment by loosebazooka** [comment]
> Ok i get it, although i think the error message could be more specific

This is true, we can update the message.

**Comment by RayDiazVega** [comment]
Ok, everything has become much clearer to me, thanks to both for the help.

**Comment by Ranjith0311** [comment]
Please make your packaging to 'war'

in pom.xml
`<packaging>war</packaging>`
